# Generated by Django 5.2.7 on 2025-11-03 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_cozinha', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_saude_medio', models.SmallIntegerField(blank=True, null=True)),
                ('emblema_sustentavel', models.BooleanField(default=False)),
                ('emblema_cardapio_metrificado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurantes.endereco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_centavos', models.IntegerField()),
                ('calorias_kcal', models.IntegerField(blank=True, null=True)),
                ('proteinas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carboidratos_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('gorduras_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sodio_mg', models.IntegerField(blank=True, null=True)),
                ('eh_vegano', models.BooleanField(default=False)),
                ('eh_vegetariano', models.BooleanField(default=False)),
                ('contem_leite', models.BooleanField(default=False)),
                ('contem_nozes', models.BooleanField(default=False)),
                ('contem_ovo', models.BooleanField(default=False)),
                ('contem_gluten', models.BooleanField(default=False)),
                ('contem_frutos_do_mar', models.BooleanField(default=False)),
                ('contem_soja', models.BooleanField(default=False)),
                ('contem_acucar', models.BooleanField(default=False)),
                ('contem_alcool', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to='restaurantes.restaurante')),
            ],
        ),
    ]
